### ISSUE TITLE
return data on how long miner has been up and running and power mode its in

### ISSUE THREAD

**Issue by gav1111** [UpstreamData/pyasic#50]
A nice feature would be to include in get_miner_data information on how long miner has been up and what power mode its in.

**Comment by UpstreamData** [comment]
Run time is a good idea, something so can work on for sure.  I have a bit of a backlog of things first, like adding LuxOS support, but that would be a good thing to add to get_data.

LPM is tough (see my comments on #49), since power_limit is already in there, but for X19 and non tuning miners I think a good option would be to measure power used by LPM and then set the power_limit value to whatever that value is when it's in LPM, and the normal power level when it's not.  You can also call get_config and then compare to the X19MinerMode.

**Comment by UpstreamData** [comment]
Added an uptime check for the more common models in 0.36.2, let me know if it has any issues.

**Comment by gav1111** [comment]
uptime returns 0 even for new gen miners

**Comment by UpstreamData** [comment]
Which type of miner?  Can you send the output of the api command stats and summary?  That's where it should show up...

**Comment by gav1111** [comment]
S17 pro, S17+, Avalong, Whatsminer M30S, S19, T19, S19 Pro, S19j Pro. Here is api results for a S19 Pro

```
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'DEVS': [{'ASC': 0,
           'Accepted': 396444,
           'Device Elapsed': 2197341,
           'Device Hardware%': 0.0,
           'Device Rejected%': 0.0,
           'Diff1 Work': 0,
           'Difficulty Accepted': 52006019072,
           'Difficulty Rejected': 10223616,
           'Enabled': 'Y',
           'Hardware Errors': 0,
           'ID': 0,
           'Last Share Difficulty': 1687903241,
           'Last Share Pool': 0,
           'Last Share Time': 1687903241,
           'Last Valid Work': 1687903241,
           'MHS 5s': 0.0,
           'MHS av': 0.0,
           'Name': 'BTM_SOC',
           'Rejected': 78,
           'Status': 'Alive',
           'Tenperature': 0.0,
           'Total MH': 0.0,
           'Utility': 0.0}],
 'STATUS': [{'Code': 9,
             'Description': 'cgminer 1.0.0',
             'Msg': '1 ASC(s)',
             'STATUS': 'S',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903255}],
 'id': 1}
{'POOLS': [{'Accepted': 396412,
            'Best Share': 229146072015.0,
            'Diff': '131K',
            'Diff1 Shares': 0,
            'Difficulty Accepted': 52005494784.0,
            'Difficulty Rejected': 10223616.0,
            'Difficulty Stale': 0.0,
            'Discarded': 1190627,
            'Get Failures': 8,
            'Getworks': 97277,
            'Has GBT': False,
            'Has Stratum': True,
            'Last Share Difficulty': 131072.0,
            'Last Share Time': '0:00:14',
            'Long Poll': 'N',
            'POOL': 0,
            'Pool Rejected%': 0.0,
            'Pool Stale%%': 0.0,
            'Priority': 0,
            'Proxy': '',
            'Proxy Type': '',
            'Quota': 1,
            'Rejected': 78,
            'Remote Failures': 0,
            'Stale': 97,
            'Status': 'Alive',
            'Stratum Active': True,
            'Stratum URL': '',
            'URL': ',
            'User': ''},
           {'Accepted': 24,
            'Best Share': 13554243.0,
            'Diff': '16.4K',
            'Diff1 Shares': 0,
            'Difficulty Accepted': 393216.0,
            'Difficulty Rejected': 0.0,
            'Difficulty Stale': 0.0,
            'Discarded': 11,
            'Get Failures': 0,
            'Getworks': 11,
            'Has GBT': False,
            'Has Stratum': True,
            'Last Share Difficulty': 16384.0,
            'Last Share Time': '268:36:10',
            'Long Poll': 'N',
            'POOL': 1,
            'Pool Rejected%': 0.0,
            'Pool Stale%%': 0.0,
            'Priority': 1,
            'Proxy': '',
            'Proxy Type': '',
            'Quota': 1,
            'Rejected': 0,
            'Remote Failures': 0,
            'Stale': 148,
            'Status': 'Alive',
            'Stratum Active': False,
            'Stratum URL': '',
            'URL': '',
            'User': ''},
           {'Accepted': 8,
            'Best Share': 3848550.0,
            'Diff': '16.4K',
            'Diff1 Shares': 0,
            'Difficulty Accepted': 131072.0,
            'Difficulty Rejected': 0.0,
            'Difficulty Stale': 0.0,
            'Discarded': 4,
            'Get Failures': 0,
            'Getworks': 11,
            'Has GBT': False,
            'Has Stratum': True,
            'Last Share Difficulty': 16384.0,
            'Last Share Time': '195:41:21',
            'Long Poll': 'N',
            'POOL': 2,
            'Pool Rejected%': 0.0,
            'Pool Stale%%': 0.0,
            'Priority': 2,
            'Proxy': '',
            'Proxy Type': '',
            'Quota': 1,
            'Rejected': 0,
            'Remote Failures': 0,
            'Stale': 77,
            'Status': 'Alive',
            'Stratum Active': False,
            'Stratum URL': '',
            'URL': '',
 'STATUS': [{'Code': 7,
             'Description': 'cgminer 1.0.0',
             'Msg': '3 Pool(s)',
             'STATUS': 'S',
             'When': 1687903255}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903256}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903256}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903256}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903256}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903256}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903256}],
 'id': 1}
{'STATS': [{'BMMiner': '1.0.0',
            'CompileTime': 'Thu Jun 9 13:06:22 CST 2022',
            'Miner': 'uart_trans.1.3',
            'Type': 'Antminer S19 Pro'},
           {'Calls': 0,
            'Elapsed': 2197343,
            'GHS 5s': 100187.5,
            'GHS av': 101932.72,
            'ID': 'BTM_SOC0',
            'Max': 0,
            'Min': 99999999,
            'Mode': 2,
            'STATS': 0,
            'Wait': 0,
            'chain_acn1': 126,
            'chain_acn2': 126,
            'chain_acn3': 126,
            'chain_acn4': 0,
            'chain_acs1': ' ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo '
                          'ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo '
                          'ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo '
                          'ooo ooo ooo ooo',
            'chain_acs2': ' ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo '
                          'ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo '
                          'ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo '
                          'ooo ooo ooo ooo',
            'chain_acs3': ' ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo '
                          'ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo '
                          'ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo '
                          'ooo ooo ooo ooo',
            'chain_acs4': '',
            'chain_hw1': 38,
            'chain_hw2': 49,
            'chain_hw3': 109,
            'chain_hw4': 0,
            'chain_rate1': '34436.70',
            'chain_rate2': '32457.58',
            'chain_rate3': '33293.21',
            'chain_rate4': '',
            'fan1': 6000,
            'fan2': 6000,
            'fan3': 6000,
            'fan4': 6000,
            'fan_num': 4,
            'freq1': 525,
            'freq2': 525,
            'freq3': 525,
            'freq4': 0,
            'frequency': 525,
            'miner_count': 3,
            'miner_id': 'no miner id now',
            'miner_version': 'uart_trans.1.3',
            'no_matching_work': 196,
            'rate_30m': 101360.62,
            'rate_unit': 'GH',
            'temp1': 69,
            'temp2': 70,
            'temp2_1': 74,
            'temp2_2': 75,
            'temp2_3': 75,
            'temp3': 70,
            'temp_chip1': '62-62-74-74',
            'temp_chip2': '66-66-75-75',
            'temp_chip3': '64-64-75-75',
            'temp_chip4': '0-0-0-0',
            'temp_max': 0,
            'temp_num': 3,
            'temp_pcb1': '57-57-69-69',
            'temp_pcb2': '61-61-70-70',
            'temp_pcb3': '59-59-70-70',
            'temp_pcb4': '0-0-0-0',
            'temp_pic1': '47-47-59-59',
            'temp_pic2': '51-51-60-60',
            'temp_pic3': '49-49-60-60',
            'temp_pic4': '0-0-0-0',
            'total rate': 101932.72,
            'total_acn': 378,
            'total_freqavg': 525,
            'total_rateideal': 100000.0}],
 'STATUS': [{'Code': 70,
             'Description': 'cgminer 1.0.0',
             'Msg': 'CGMiner stats',
             'STATUS': 'S',
             'When': 1687903256}],
 'id': 1}
{'STATUS': [{'Code': 11,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Summary',
             'STATUS': 'S',
             'When': 1687903256}],
 'SUMMARY': [{'Accepted': 396444,
              'Best Share': 229146072015,
              'Device Hardware%': 0.0,
              'Device Rejected%': 0.0,
              'Difficulty Accepted': 52006019072.0,
              'Difficulty Rejected': 10223616.0,
              'Difficulty Stale': 0.0,
              'Discarded': 1190642,
              'Elapsed': 2197343,
              'Found Blocks': 0,
              'GHS 30m': 101369.78,
              'GHS 5s': 99857.65,
              'GHS av': 101932.76,
              'Get Failures': 8,
              'Getwork': 97299,
              'Hardware Errors': 196,
              'Last getwork': 1687903255,
              'Local Work': 1286987,
              'Network Blocks': 3676,
              'Pool Rejected%': 0.0,
              'Pool Stale%': 0.0,
              'Rejected': 78,
              'Remote Failures': 0,
              'Stale': 322,
              'Total MH': 223955645370000.0,
              'Utility': 10.82,
              'Work Utility': 1420340.18}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903256}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903256}],
 'id': 1}
{'STATUS': [{'Code': 22,
             'Description': 'cgminer 1.0.0',
             'Msg': 'CGMiner versions',
             'STATUS': 'S',
             'When': 1687903256}],
 'VERSION': [{'API': '3.1',
              'BMMiner': '1.0.0',
              'CompileTime': 'Thu Jun 9 13:06:22 CST 2022',
              'Miner': 'uart_trans.1.3',
              'Type': 'Antminer S19 Pro'}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903257}],
 'id': 1}
misha@debianexp:~/temp/pyasic$ {'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903253}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
             'When': 1687903254}],
 'id': 1}
{'STATUS': [{'Code': 14,
             'Description': 'cgminer 1.0.0',
             'Msg': 'Invalid command',
             'STATUS': 'E',
```

**Comment by UpstreamData** [comment]
Had to be at index 1 instead of 0, should be fixed in 0.36.4.

**Comment by gav1111** [comment]
updated but still getting a zero:
`,model=S19,hostname=Unknown uptime=0,make="AntMiner",api_ver="0.0.0",fw_ver="Tue Dec  6 16:10:00 CST 2022",hashrate=74.63,nominal_hashrate=74.57,`

**Comment by UpstreamData** [comment]
Is this using the script with the `data_to_get` list set?  If so you have to make sure to add `uptime` in there.

**Comment by gav1111** [comment]
oh my bad

**Comment by gav1111** [comment]
Is it possible to incorporate X19MinerMode in get_data() request?

**Comment by UpstreamData** [comment]
I'm considering replacing the `is_mining` check with an enum that would have `mining`, `tuning`, `low_power`, `failed`, and `stopped`.  Then `is_mining` would check for values other than `stopped`, and you would also be able to check that mode through that attribute, maybe call it `miner_state`?

**Comment by gav1111** [comment]
Yes that would be very useful I think. miner_state seems like the appropriate attribute.

**Comment by UpstreamData** [comment]
Aiming to have this as part of #73 ideally, and just have it as part of the micro config.

**Comment by UpstreamData** [comment]
This will be part of the config once #76 gets merged, it is a bit more to query but should work.

**Comment by UpstreamData** [comment]
#81 adds support for this directly into `MinerData`.
